version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hxhc-api-app
    container_name: hxhc_app
    restart: unless-stopped
    env_file:
      - ./src/.env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./src:/var/www
      - composer_cache:/home/laravel/.composer/cache
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3
    container_name: hxhc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hxhc
      MYSQL_USER: hxhc
      MYSQL_PASSWORD: secret
      TZ: Europe/Paris
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"

  nginx:
    image: nginx:1.26-alpine
    container_name: hxhc_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db_data:
  composer_cache:
