services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: hxhc
      MYSQL_USER: hxhc
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    volumes: null
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.26-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/public:/var/www/public:ro
    depends_on:
      - app
