name: Docker Build & Smoke-Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  compose-up:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: docker compose up
        run: docker compose up -d --build

      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -fs http://localhost:8080/cards >/dev/null; then
              echo "API ready"; exit 0
            fi
            echo "Waiting ($i/20)…"
            sleep 5
          done
          echo "API did not respond in time"; docker compose logs; exit 1

      - name: Smoke check
        run: curl -s http://localhost:8080/cards | jq .

      - name: docker compose down
        if: always()
        run: docker compose down -v
