name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fake .env for CI
        run: |
          mkdir -p src
          printf "APP_KEY=base64:dummykey=\nAPP_ENV=testing\n" > src/.env

      - name: Build & start stack
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            up -d --build

      - name: Wait for /cards endpoint
        run: |
          for i in {1..20}; do
            if curl -fs http://localhost:8080/cards >/dev/null; then
              exit 0
            fi
            sleep 5
          done
          docker compose -f docker-compose.yml -f docker-compose.ci.yml logs
          exit 1

      - name: Shutdown stack
        if: always()
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            down -v
